### PR TITLE
Update story 2nd time

### PR DESCRIPTION
**Pull request by disha2292**
I want to merge this but if you'd merge I won't be able to learn how to remove commits or how to work with same PR again and again, so this time do not approve but ask for changes.

### CODE REVIEW

**Review by jayygokani — COMMENTED** [review]
It is my repo so I will have to merge after reviewing. You would not be allowed to do the same.

**Comment by disha2292** [comment]
aree i know ! but merge it now ! i deleted your lines to resolve conflict !

**Comment by disha2292** [comment]
add your lines after my line it fits there !

**Comment by disha2292** [comment]
and do it ASAP so i can update again!

**Review by jayygokani — APPROVED** [review]

**Pull request merged**
